### ISSUE TITLE
Several sidebar links don't do anything

### ISSUE THREAD

**Issue by wearhere** [npm/docs#1017]
These ones highlighted in red:

![image](https://user-images.githubusercontent.com/110000/41368365-94dceaf4-6ef6-11e8-92ba-a8bc14b922f9.png)

They become red when clicked, but don't unfold (like "npm, Inc." does below them), or direct to any other page.

**Comment by KenanY** [comment]
Cannot reproduce with Firefox v61.

**Comment by wearhere** [comment]
I can confirm that these links work now (in Chrome 66 fwiw). (Perhaps their fix is related to whatever fixed #1016 ? Makes me feel like I should have taken videos of these bugs 😛 ) Anyhow thanks for the the quick and polite response, closing.
