### ISSUE TITLE
Internal section links should get converted to real links

### ISSUE THREAD

**Issue by seldo** [npm/docs#106]
This used to happen but there's apparently been a regression in how we build the docs site, e.g. on https://docs.npmjs.com/misc/config

The phrase "npm-scripts(7)" should be a link to https://docs.npmjs.com/misc/scripts (7=misc). And the "See also" links at the bottom should also link to https://docs.npmjs.com/cli/run-script etc.

Trivia: what do the section numbers mean?
http://unix.stackexchange.com/questions/3586/what-do-the-numbers-in-a-man-page-mean

In our case:
1 = docs.npmjs.com/cli
3 = docs.npmjs.com/api
5 = docs.npmjs.com/files
7 = docs.npmjs.com/misc

**Comment by develup** [comment]
+1

**Comment by al-the-x** [comment]
@zeke @seldo Can one of you chaps point me at the code for generating the documentation and maybe some background on the generation build process? Happy to submit a patch, as this is very annoying when teaching... O_O

**Comment by ChicagoDev** [comment]
I find it odd that my patch would fail CI testing. I merely added links to the `doc/misc/npm-config.md` file. 

I was having trouble understanding the workflow for contributing to this docs repository directly. Thus, I tried patching directly to Node. If someone would like to try and help me understand the workflow of contributing here to docs, could you send me an email to the address in my profile? 

I tried forking this repo and performing `npm run dev` but my changes were not appearing when I was testing locally. 

I'd like to help with the section links, which I noticed are needed in other areas of the docs as well. Thanks.

**Comment by ashleygwilliams** [comment]
this was solved in d64a1f60bf8bc533d1864b31319d4c806a389bc7. closing.
