### ISSUE TITLE
Document constraints for "name" field in package.json

### ISSUE THREAD

**Issue by zeusdeux** [npm/docs#108]
The rules that I know of are listed below.

The package names:

- must be lowercase
- can have hyphens
- must not have any non url safe characters
- shouldn't start with a dot or underscore

Could we add other such rules to the list above and document them [here](https://docs.npmjs.com/files/package.json) and [here](https://docs.npmjs.com/getting-started/publishing-npm-packages)?

I can send a PR once we have the rules in place.

**Comment by zeke** [comment]
Good idea, @zeusdeux. Here's a codified representation of the package name rules: https://github.com/npm/validate-npm-package-name. Wanna start with a PR to that repo that summarizes the rules in `README.md`?

**Comment by zeusdeux** [comment]
Yeah I can do that @zeke. Just one question, are there any other rules other than the four that I have listed and the ones that are spread in the docs?

**Comment by zeke** [comment]
Yes, there are more rules. See these tests: https://github.com/npm/validate-npm-package-name/blob/master/test/index.js

Note that the rules differ slightly between new and existing names. There are packages in the registry with names that would be considered invalid for creation today, for many reasons: They're too long, the contain uppercase characters, etc. But your original list captures the most important aspects of name validation.

**Comment by zeusdeux** [comment]
npm/validate-npm-package-name#3
