### ISSUE TITLE
Naming: "Node modules" should be "Node packages", right?

### ISSUE THREAD

**Issue by martinheidegger** [npm/docs#111]
> Node.js modules are one kind of package

[link](https://github.com/npm/docs.npmjs.com/blob/385274e8279269c9180bfcc330d96354b8c0105a/content/getting-started/creating-node-modules.md#creating-nodejs-modules)

In my understanding of how node works: every JavaScript file is a `module` (basically). A module may or may not use `exports` or `module.exports` to offer data to the outside. If a folder has a `package.json` file it becomes a  package. So it would make more sense to me if there was written like `Node.js packages are packages that contain Node.js modules.

**Comment by ashleygwilliams** [comment]
hey @martinheidegger - so the way i read it, this text suggests that a `node module` is one type of code that could be put in an `npm package`, as opposed to say some clientside js, etc. given that do you still think it should be changed?

**Comment by ashleygwilliams** [comment]
this should be clarified by the `packages.md` in the new `how npm works` guide via #479. would love your feedback @martinheidegger

**Comment by martinheidegger** [comment]
@ashleygwilliams This section: https://github.com/npm/docs/blob/f65f5a23de1ff4b2064f56d367ae3a99a6d49e46/content/how-npm-works/packages.md#tldr clarifies that issue perfectly. Closing this issue as happy npm "customer" :+1:

**Comment by ashleygwilliams** [comment]
:)
