### ISSUE TITLE
npm config set ca="" doesn't work

### ISSUE THREAD

**Issue by windhandel** [npm/docs#113]
We've experimented with several variations of the set ca call to no avail.  This command doesn't seem to work.  However, setting ca using the config set cafile command seems to work successfully.

However, if you do not set the cafile with an absolute file path then the cafile always uses a relative path to wherever you are at the time of using npm.  I suspect that you should convert the relative path of the cafile to an absolute path rather than having npm look for a roving cafile wherever you go.

BTW, this is on a Windows 8 machine with Node v0.10.35.

**Comment by ashleygwilliams** [comment]
hi @windhandel ! this is an issue with the CLI, and should be refiled in the CLI repo. thanks! closing.
