### ISSUE TITLE
Code block on docs.npmjs.com/misc/semver looks objectively "poor"

### ISSUE THREAD

**Issue by pdehaan** [npm/docs#126]
per https://github.com/npm/npm/pull/7400

> Because it looks like using "javascript" [in the codefence] was causing the rest of the page to be rendered inside a code block.

> https://github.com/npm/npm/blob/master/doc/misc/semver.md looks fine on GitHub.
> https://github.com/npm/node-semver/blob/master/README.md looks fine on GitHub.
> https://docs.npmjs.com/misc/semver looks objectively "poor".

**Comment by ashleygwilliams** [comment]
this appears to be fixed now. closing. @pdehaan please reopen if you still see the problem.
