### ISSUE TITLE
Document how to interpret "See npm-xxxxxxx(n) blah blah blah."

### ISSUE THREAD

**Issue by sewelljw** [npm/docs#128]
Document how to interpret references like "See npm-folders(5) to learn about where npm puts stuff."
These are not links. I looked around the site trying to find it, but failed. I suggest an entry on https://docs.npmjs.com/ just above "Getting Started"

**Comment by KenanY** [comment]
Yeah they should be linkified (https://github.com/npm/docs.npmjs.com/issues/106)

**Comment by palanik** [comment]
+1

**Comment by ashleygwilliams** [comment]
yes! we are looking into a strategy for outputting both man and html format to eliminate this definitely weird thing.

**Comment by ashleygwilliams** [comment]
hello! this was fixed in d64a1f60bf8bc533d1864b31319d4c806a389bc7. closing.
