### ISSUE TITLE
Duplicate `files` ID in package.json Documentation DOM

### ISSUE THREAD

**Issue by destroyerofbuilds** [npm/docs#131]
There are two elements on the [package.json](https://docs.npmjs.com/files/package.json) page that contain the ID `files`. One is associated with the _Configuring npm_ navigation section, while the other is associated with the `files` property documentation.

Therefore links like [https://docs.npmjs.com/files/package.json#files](https://docs.npmjs.com/files/package.json#files) do not actually navigate to the `files` property documentation as I would expect.

**Comment by hemanth** [comment]
Came here to fix the same, but I didn't find the files related to `package.json` in the `contents` dir.

**Comment by ljharb** [comment]
This is actually a problem with the entire page overall - I see multiple `id="getting-started"` occurrences, and HTML IDs are supposed to be unique on the page. Perhaps things are getting auto-generated here, and the generation algorithm is flawed?

**Comment by hemanth** [comment]
>  HTML IDs are supposed to be unique on the page.

^ Yes. Where can we find the `generator` script?

**Comment by hemanth** [comment]
@ljharb As you suspected that algorithm seems to be flawed, I just found the below duplicates, just in `package.json` page:

```sh
#description
#files
#getting-started
#private-modules
#misc
#enterprise
#cli
#files
#api
#policies
```

**Comment by TrySound** [comment]
Three id="files" on the page disturb to show mainteiners these option. But it's very improtant.

**Comment by ashleygwilliams** [comment]
fixed in #367

**Comment by ljharb** [comment]
Thanks @ashleygwilliams!

**Comment by hemanth** [comment]
Nice, that was a cheeky one liner: `<section {{#equal id ../page.section}}class="active"{{/equal}}>`
