### ISSUE TITLE
Document package name restrictions

### ISSUE THREAD

**Issue by zeke** [npm/docs#149]
- max length is 214 characters
- lowercase only
- no core module names
- encodeURIComponent(name) === name

**Comment by seldo** [comment]
The most obvious place to note (or at least link to) these restrictions is in the CLI documentation, here:
https://github.com/npm/npm/blob/master/doc/files/package.json.md#name

**Comment by linclark** [comment]
See npm/npm#8144

**Comment by zeke** [comment]
Thank you, @linclark!
