### ISSUE TITLE
"Send a Pull Request" link goes to npm/npm repo

### ISSUE THREAD

**Issue by kevinSuttle** [npm/docs#157]
Is this intentional? 
e.g. The link at the bottom of this page https://docs.npmjs.com/cli/dedupe points to https://github.com/npm/npm/edit/master/doc/cli/npm-dedupe.md.

**Comment by linclark** [comment]
Yes, for some pages on the docs site we end up pulling directly from npm's man pages. That might change sometime in the future, but for now that is where you would file the pull request for that page.

**Comment by kevinSuttle** [comment]
Gah. https://github.com/npm/npm/issues/8338

**Comment by linclark** [comment]
Ah, ok, sorry for the confusion. The link generation would be something that would happen in this code. The actual content is generated from npm.

**Comment by kevinSuttle** [comment]
Oh I see. Makes sense. Thanks @linclark.
