### ISSUE TITLE
Previous docs had in-document navigation down the right

### ISSUE THREAD

**Issue by iarna** [npm/docs#16]
Contrast:

https://docs.npmjs.com/files/package.json

https://www.npmjs.org/doc/files/package.json.html

This was pretty useful, and it'd be nice to see it exposed somewhere, though not necessarily in the same place.

**Comment by ashleygwilliams** [comment]
these two links now go to the same page so it is not useful. please add comments about design on this thread now https://github.com/npm/docs/issues/439 (if you, @iarna or @othiym23 have screenshots from the last site that would be useful)
