### ISSUE TITLE
"How to publish private modules" standalone tutorial

### ISSUE THREAD

**Issue by seldo** [npm/docs#168]
We have docs on publishing, and on scope, but there should be a simple 5-step zero-to-private-modules tutorial.

**Comment by linclark** [comment]
I had an idea for how to better explain this based on the discussion I saw on Twitter today and conversations with Stephanie earlier.

I created a screencast, https://youtu.be/Tm0I7_PJj9Y. We can also write out the instructions. 

Let me know if this is what you were thinking.

@snopeks @ehsalazar I'd also love your feedback based on the interactions you've been having with users who have been struggling. Any feedback or ideas are welcome :)

**Comment by seldo** [comment]
This is great stuff!

**Comment by snopeks** [comment]
@linclark this is so well done! Very explanatory, covers the details that a lot of users (including me!) have had issues with, namely scope, npm version, access, & making sure to logout/login again. Very helpful. I'll get back to you with more feedback if/when it comes to me.

**Comment by linclark** [comment]
I added this in #169. I ended up just replacing the existing publishing docs because there was so much overlap.
