### ISSUE TITLE
Correction to docs.npmjs.com/api/view

### ISSUE THREAD

**Issue by ehsalazar** [npm/docs#174]
This section mistakenly makes use of single quotes around the version number. 

>If a version range is provided, then data will be printed for every matching version of the package. This will show which version of jsdom was required by each matching version of yui3:

As documented: 
```
npm.commands.view(["yui3@'>0.5.4'", "dependencies.jsdom"], callback)
```
It should be: 
```
npm.commands.view(["yui3@>0.5.4", "dependencies.jsdom"], callback)
```

**Comment by KenanY** [comment]
@ehsalazar done :tada:

**Comment by ashleygwilliams** [comment]
this seems fixed. closing.
