### ISSUE TITLE
Update Developer Guide .npmignore Section to Match package.json Spec

### ISSUE THREAD

**Issue by mjhasbach** [npm/docs#182]
[Developer Guide](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package):
```
The following paths and files are never ignored, so adding them to .npmignore is pointless:

package.json
README.*
```

[package.json Spec](https://docs.npmjs.com/files/package.json#files):
```
Certain files are always included, regardless of settings:

package.json
README (and its variants)
CHANGELOG (and its variants)
LICENSE / LICENCE
```

I would have submitted a PR for this, but I was unable to find the Developer Guide in this repo.

**Comment by KenanY** [comment]
@mjhasbach [here you go](https://github.com/npm/npm/blob/1fa9169ac9687f0be4156574279a968a48dd2458/doc/misc/npm-developers.md) :)

**Comment by mjhasbach** [comment]
Ahh, cool. I'll open the PR over there. Thanks!
