### ISSUE TITLE
Show command name atop CLI pages

### ISSUE THREAD

**Issue by zeke** [npm/docs#22]
Via @othiym23:

> hey, I know you're probably overwhelmed right now, so I don't want to add to the load, but after looking at the docs site on my phone, it feels very strange to me to not have the name of the API command at the top of the page, and just have the description there

**Comment by ashleygwilliams** [comment]
@othiym23 i assume you still feel this way? gonna add this next.

**Comment by othiym23** [comment]
@ashleygwilliams yes indeed, this would be useful.
