### ISSUE TITLE
Misleading `npm prepublish` docs

### ISSUE THREAD

**Issue by jenius** [npm/docs#28]
The docs on the site for npm scripts contains the following statement:

> If you have to do other things before your package is used, in a way that is not dependent on the operating system or architecture of the target system, then use a prepublish script instead. This includes tasks such as:

> - Compile CoffeeScript source code into JavaScript.
> - Create minified versions of JavaScript source code.
> - Fetching remote resources that your package will use.

Unfortunately, this is not actually the case for at least 2 of the listed examples. Since `prepublish` is also run on local `npm install` with no arguments, it's not actually feasible to use prepublish for most cases (aside: this is a counter-intuitive and poor decision and [numerous](https://github.com/npm/npm/issues/3059) [issues](https://github.com/npm/npm/issues/6394) [have](https://github.com/npm/npm/issues/4338) [been]() [opened](https://github.com/rlidwka/yapm/issues/12) in the npm repo with people complaining about it, but alas isaacs seems super determined to not change it). For example, if you were to use prepublish to compile coffeescript or minify assets, anyone who pulls down your project from github to contribute and uses `npm install` to install dependencies, which is the standard practice with all node packages, will also have the project compiled/minified so that they cannot correctly contribute.

The solution that has been suggested in some of the issues is that you use a Makefile instead. For this reason I have a Makefile like [this](https://github.com/jenius/accord/blob/master/Makefile) in all my projects that use coffeescript, and instead of using `npm publish .` I use `make publish` so that it's compiled correctly but without hindering contribution.

To avoid having other authors who plan to use `npm prepublish` in any potentially useful way fall into the trap of assuming it actually does what it says, I feel like the docs should be a little more clear about this.

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/docs/issues/498
