### ISSUE TITLE
Omg bundledDependencies docs are so bad

### ISSUE THREAD

**Issue by seldo** [npm/docs#372]
https://docs.npmjs.com/files/package.json#bundleddependencies

**Comment by ashleygwilliams** [comment]
@seldo would love some more info here please! thx

**Comment by seldo** [comment]
`bundledDependencies` is a stanza in package.json that allows you to pack up dependencies into the package tarball itself. Some projects use this to save download time, and npm uses it extensively to bundle itself into a single file. There are absolutely zero outstanding docs about what this feature does or how to use it. Quiz the CLI team about how it works, and write that stuff down :-)

**Comment by ashleygwilliams** [comment]
this is a CLI docs issue.

refiled for you here: https://github.com/npm/npm/issues/10972
