### ISSUE TITLE
npm Enterprise -> npm On-site

### ISSUE THREAD

**Issue by mmalecki** [npm/docs#374]

**Comment by ashleygwilliams** [comment]
would really appreciate some more info here @mmalecki @bcoe.  thanks!

**Comment by lewiscowper** [comment]
My guess is that all references to "npm Enterprise" need to be changed to "npm On-Site"

For example, everything inside here, and the slug itself: (there could be more) https://docs.npmjs.com/enterprise/index

**Comment by nexdrew** [comment]
Addressed by #445.

**Comment by ashleygwilliams** [comment]
as @nexdrew mentioned this has been solved. closing.
