### ISSUE TITLE
many npm options are not listed anywhere in documentation

### ISSUE THREAD

**Issue by spikegrobstein** [npm/docs#390]
Many times, in the documentation for the NPM actions, an exhaustive list of available options for that action are not shown. I've had trouble finding documentation on options that I *know* exist as well as have had trouble finding out whether options that *should* exist are real or actually do what I expect.

The best example is the `install` page (https://docs.npmjs.com/cli/install) doesn't list the `--deployment` flag anywhere, and only passively mentions `--production` down the page, hidden in a paragraph.

It would be really great if there was a table of the available options and what they do in one place.

**Comment by accraze** [comment]
@spikegrobstein i can't seem to find the `--deployment` flag anywhere in the src.... is it only used with `install`?

**Comment by KenanY** [comment]
@accraze [As far as I know](https://github.com/npm/npm/issues/10069#issuecomment-150055555), it isn't.

**Comment by spikegrobstein** [comment]
I thought so. I don't have access to the old code from my last job, but maybe it was a mistake on their end. If so, sorry for wasting your time!

(Holy crap that's embarrassing)

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/npm/issues/10970
