### ISSUE TITLE
npm Docs look strange when the heading extends over multiple lines.

### ISSUE THREAD

**Issue by lewiscowper** [npm/docs#396]
![screen shot 2015-10-22 at 16 18 24](https://cloud.githubusercontent.com/assets/593574/10667639/a1312aca-78d8-11e5-9e82-b0e86029b33c.png)

I genuinely just tried to look for the missing link that would have gone ahead of "about npm configuration". An easy fix would be to shorten the "heading" in the metadata of each thing, but maybe there's some CSS thing that would make the line spacing shorter when it was overflowing. I'll add some more examples, (which could probably be re-written to be shorter without a huge deal).

![screen shot 2015-10-22 at 16 21 22](https://cloud.githubusercontent.com/assets/593574/10667732/22f6cf4c-78d9-11e5-8f9a-bb4a4a8e322a.png)
![screen shot 2015-10-22 at 16 23 32](https://cloud.githubusercontent.com/assets/593574/10667756/42d33148-78d9-11e5-9d98-8f0f9d6b6980.png)
![screen shot 2015-10-22 at 16 23 26](https://cloud.githubusercontent.com/assets/593574/10667757/4415a9a0-78d9-11e5-9a30-f2e16415cc64.png)
![screen shot 2015-10-22 at 16 23 12](https://cloud.githubusercontent.com/assets/593574/10667749/3647bc00-78d9-11e5-91fb-73c3ce62cf0b.png)
![screen shot 2015-10-22 at 16 23 50](https://cloud.githubusercontent.com/assets/593574/10667763/4eeac2e8-78d9-11e5-833f-1ec34a6506d1.png)

**Comment by ashleygwilliams** [comment]
closing in favor of https://github.com/npm/docs/issues/439 which is the issue for the docs redesign.
