### ISSUE TITLE
no --userconfig commandline option documented

### ISSUE THREAD

**Issue by spikegrobstein** [npm/docs#404]
I just made a feature request on the main npm repo for a method to specify a `.npmrc` for a specific run of `npm` it turns out that there is a `--userconfig` option that is not shown in the docs.

Could it please be added to:

https://docs.npmjs.com/misc/config

EDIT: I've learned that technically it is documented, but not as a commandline option. can this be made more explicit?

**Comment by KenanY** [comment]
@spikegrobstein Since everything on that page can be passed as a command-line option, would it be best to simply have [a note at the top of the page](https://docs.npmjs.com/misc/config#command-line-flags) saying that you can pass everything as a command-line option?

**Comment by spikegrobstein** [comment]
I would say no. for myself, documentation pages like this, I frequently will scroll quickly through looking for what I want... generally a table, or in this case, a section that lists a bunch of `--this` `--that` stuff. If I see a block with that, I assume that's a list of available commandline options, much like is shown in a manpage.

Having a note that says "btw, these are also commandline options" is very easy to miss and is only valuable if someone is reading the page top-to-bottom.

There could be a compromise, though... if you have a blub like "each config option has a commandline option equivalent" and then in each section you have a `Commandline: --userconfig` or something along those lines, that would add a ton of value.

Scrolling fast and seeing those `--some-option` incline code spans would stand out and make it more obvious.

how's that sound?

**Comment by spikegrobstein** [comment]
Another request, that's really part of this, is also including the `NPM_CONFIG_` environment variable that can override these settings. 

Would it be possible to include that for each setting?

**Comment by ashleygwilliams** [comment]
this request is in regards to a CLI doc which lives in the CLI repo (npm/npm). i've filed an issue there with this content: https://github.com/npm/npm/issues/10970. closing.
