### ISSUE TITLE
Run scripts doc holes

### ISSUE THREAD

**Issue by seldo** [npm/docs#408]
How run scripts work are documented here:
https://docs.npmjs.com/misc/scripts#package-json-vars

But these are only barely connected to the "run" command docs here:
https://docs.npmjs.com/cli/run-script

These two should be better cross-referenced or possibly combined.

**Comment by ashleygwilliams** [comment]
this is a CLI docs issue, should be in the CLI repo. 
i have filed an issue for it here: https://github.com/npm/npm/issues/10971
i have also filed an issue to create a scripts guide here: https://github.com/npm/docs/issues/498

closing in favor of the 2 aforementioned issues.
