### ISSUE TITLE
WARN on `npm run dev`

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/docs#413]
```
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
```

**Comment by noffle** [comment]
`autoprefixer` is depended on via `terraform`, which appears to have updated to [`autoprefixer@6.1.0`](https://github.com/sintaxi/terraform/commit/b433a06af07f7ea8aa80b72aabd16b381dcc97aa). I can't repro this WARN on my end with HEAD.

**Comment by ashleygwilliams** [comment]
thanks @noffle!

**Comment by ashleygwilliams** [comment]
seems to have been fixed via @noffle's comment. i also can no longer repro. closing.
