### ISSUE TITLE
"Scoped packages" page and npm version

### ISSUE THREAD

**Issue by danpaz** [npm/docs#417]
The [scope page](https://docs.npmjs.com/misc/scope) mentions:

> (As of 2015-04-19, the public npm registry does support scoped packages)

I'm not sure exactly when scoping became supported, though that date does line up with [v2.0.0-beta3 in the changelog](https://github.com/npm/npm/blob/master/CHANGELOG.md#v200-beta3-2014-09-04).

If publishing/installing scoped packages depends on npm 2 maybe the documentation can clarify that? I know I've had some heartache trying to install private modules and getting a 404 only to realize I was on npm 1.4.

**Comment by KenanY** [comment]
Coincidentally [`npm@1.4.29`](https://github.com/npm/npm/releases/tag/v1.4.29) was just released which intentionally crashes when trying to install scoped packages :) (arguably not a substitute for more documentation)

**Comment by danpaz** [comment]
Wow, released an hour ago :smile:.

**Comment by ashleygwilliams** [comment]
this is mentioned in the private modules guide as of https://github.com/npm/docs/commit/e1ce633e8e9a5ade6afa1c0d67971672b6aac922

the scope page you mention is a CLI doc and therefore lives in the CLI repo (npm/npm). i have opened an issue for you on that repo with this content: https://github.com/npm/npm/issues/10968
