### ISSUE TITLE
installing packages locally is not windows friendly

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/docs#421]
https://docs.npmjs.com/getting-started/installing-npm-packages-locally

test says to run `ls node_modules` which will not work on windows.

pointed out in #420 thanks @lushen

**Comment by Delapouite** [comment]
This issue has been resolved by @ecowden 's PR. I think it can be closed.

**Comment by ashleygwilliams** [comment]
great! thanks for helping @Delapouite :dolphin:
