### ISSUE TITLE
`~` does not work on windows

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/docs#424]
https://docs.npmjs.com/private-modules/ci-server-config

**Comment by ashleygwilliams** [comment]
https://docs.npmjs.com/files/folders

**Comment by phildini** [comment]
@ashleygwilliams, in https://docs.npmjs.com/private-modules/ci-server-config, how important do you think it is to have the path for `~/.npmrc`? One solution for that page would be to just have `.npmrc` sans path, which I think would work for windows and posix?

**Comment by ashleygwilliams** [comment]
that's a great suggestion @phildini do you want to make a PR for that? linking to the `.npmrc` page would also help clarify! thanks for contributing :)

**Comment by phildini** [comment]
I think that PR will do it, let me know if anything more is needed. :)
