### ISSUE TITLE
.npminclude missing from developer docs

### ISSUE THREAD

**Issue by rwaldron** [npm/docs#438]
.npmignore is covered, but no mention of .npminclude

**Comment by ashleygwilliams** [comment]
this will actually be an issue in the [CLI docs][1]:
`npmignore` is currently in [`/misc/developers.md`][2], but i think the best solution is to put it in `/files/`, so `/files/.npmignore`, and then also add a `/files/.npminclude`. thoughts?

thanks for filing, @rwaldron! PRs welcome :wink: 

[1]: https://github.com/npm/npm/tree/master/doc
[2]: https://github.com/npm/npm/blob/master/doc/misc/npm-developers.md

**Comment by noffle** [comment]
I took a look -- it's probably not covered because `.npminclude` hasn't been in the codebase since [Jan 2011](https://github.com/npm/npm/commit/a1c926184ce263ebc754d62da381c8350a110cde).
