### ISSUE TITLE
Docs request: Step-by-step guide for creating NPM OnSite registry

### ISSUE THREAD

**Issue by kevinSuttle** [npm/docs#440]
Reference https://github.com/npm/docs/issues/88#issuecomment-155873683 

When one gets to the step for adding your registry URL, it's confusing, because users like me believe that's what they're attempting to do at the moment. 

cc: @bcoe @ashleygwilliams

**Comment by bcoe** [comment]
Are you talking about the registry URL that you configure in the admin-console on `:8800`, labeled:

> Full URL of npm Enterprise registry (8080 must stay constant, you may optionaly change the IP to a pretty host name)

If so this is the URL that will be populated as documents are saved to your npm On-Site appliance, it's variable so that you have the option of setting up `https`, or a CDN.

**Comment by kevinSuttle** [comment]
I don't know. From what I've read, it sounds like I need to set up a CouchDB server somewhere? I can get to a the admin dashboard, and the NPM OnSite registry UI, but there is no way to log in, manage packages, etc. The public packages don't seem to be replicated yet, as each one is empty in terms of content.

**Comment by ashleygwilliams** [comment]
just merged 4b81993410234f5446047bcbbf32e273fc26f82b by @nexdrew which is a new quickstart guide to get you up and running with npmO. should be in production by EOD. closing. please open a new issue if you continue to have questions. thanks!
