### ISSUE TITLE
Feature Request: Notify authors if an NPM module is outdated

### ISSUE THREAD

**Issue by delian** [npm/docs#449]
I see a lot of NPM modules that are outdated. Some of them cannot compile with the new Node tools, some have problems with the dependencies (the module is ok, but depend on a module that is not ok - either does not compile / work with current Node). Package.json for most of the modules does not even contain compatibility properties (with dependent modules or node version). 
It is very hard for a developer to find out what is compatible with his environment and what is not. What is outdated and what is not.
So my suggestions are all in that sense:
- To have a mechanism trough NPM to notify the authors of the module if it is outdated and not supporting the platforms it claims to support, and in a while, this module to be marked and taken out of the default search, if the author does not clear the reported state

**Comment by KenanY** [comment]
@delian So, this is a feature request for the `npm` CLI (and for the website with regards to search and whatnot)? If so, this should firstly be opened over [here](https://github.com/npm/npm/issues) and then, once the feature is implemented if it ever is, a ticket for the search part can be opened over [here](https://github.com/npm/newww/issues). This issue tracker regards the documentation site which this issue does not seem to involve.

**Comment by delian** [comment]
Thank you for that clearance. I didn't realized it is for the docs only,
but this is the URL where the npm website sends me (feature request link at
the bottom of the home page).
In essence, the feature I am looking for, should affect both the npm
(trough the minimum the search) and eventually the web site (as a potential
interface for the implementation of the reports and the clear).
I will take a better look where to send the request and modify it properly.


Delian

**Comment by ashleygwilliams** [comment]
filed issue re misleading language: https://github.com/npm/docs/issues/497
closing.
