### ISSUE TITLE
npmjs.com feature request - display package.json content on http://npmjs.com/package/<foo>

### ISSUE THREAD

**Issue by kaizhu256** [npm/docs#458]
for such an important file like package.json, which explicity reveals what the package does, you would expect it's raw contents to be readily available for perusal on the package's npm homepage

such info would tell me:
- whether its likely vaporware
- what is the package doing when i run "npm install", "npm start" or "npm run-script ..." ?
- does it have any commandline scripts?
- what are its devDependencies?
- which script is the main entry point for the package?

**Comment by KenanY** [comment]
@kaizhu256 Could you re-open this issue over [here](https://github.com/npm/newww/issues)? This issue tracker is for the documentation site.

**Comment by kaizhu256** [comment]
@KenanY done. closing this issue ; )
