### ISSUE TITLE
please update "npm i --help" with options

### ISSUE THREAD

**Issue by robey** [npm/docs#460]
I just found out about "npm i --no-progress" through an anecdote. I had assumed the feature didn't exist because it wasn't documented in "--help". It would be helpful (hee!) to update the help page with the new options.

**Comment by iarna** [comment]
`--progress` & `--no-progress` are documented in the generic config page currently, but not elsewhere. They apply to a bunch of different commands, so we might considering adding them to not just `install` but `uninstall`, `update`, `dedupe` and perhaps elsewhere.

**Comment by robey** [comment]
yeah, i would have expected to see it in "npm --help" if it was a global option, or "npm i --help" if it was specific to install, but (in 3.3.12) it's not yet in either. there's also an "npm -l" that i tried just now, and it's not there either.

**Comment by ashleygwilliams** [comment]
this is a issue regarding documentation that resides in the CLI, and therefore the CLI repo (npm/npm). i've refiled the issue there for you: https://github.com/npm/npm/issues/10967
