### ISSUE TITLE
npm logout documentation contains text from npm adduser

### ISSUE THREAD

**Issue by joedragons** [npm/docs#466]
https://docs.npmjs.com/cli/logout

Was reviewing the above page and the scope section (https://docs.npmjs.com/cli/logout#scope) seems to be directly from npm adduser including the e.g.
From what I can tell scope on logout only defines the registry to be logged out and does not remove the scope (see https://github.com/npm/npm/issues/10529).  This is relayed in "If --scope is provided, this will find the credentials for the registry connected to that scope, if set." in the main section but not reiterated in the subsection.
I would have made a PR but I'm not 100% sure this is what should be being done.
But at least I don't think the scope section should reference a "npm adduser" command.

**Comment by ashleygwilliams** [comment]
hi @joedragons! this repo copies documentation from the cli repo for the cli commands. i have opened an issue on that repo for you: https://github.com/npm/npm/issues/10966. closing.
