### ISSUE TITLE
Missing page >>> npm-rm

### ISSUE THREAD

**Issue by Stephn-R** [npm/docs#468]
This is the missing page: https://docs.npmjs.com/cli/rm

I accessed it through the link on the bottom of this page: https://docs.npmjs.com/files/package.json

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/docs/issues/452, and fixed by https://github.com/npm/npm/pull/10419 (just needs to be deployed I think).

**Comment by ashleygwilliams** [comment]
closing, as it is a dupe.
