### ISSUE TITLE
Organization docs update request

### ISSUE THREAD

**Issue by snopeks** [npm/docs#469]
Based on the current feedback, we should make it explicit that Organization users should not delete their super-admin in an attempt to change their super-admin. We will enable users to choose their super-admin in the near future, but currently it seems best that we make it clear the super-admin should not be removed. 

It would also be helpful to make a more explicit note about not deleting the developers team. Thoughts? cc @ashleygwilliams

**Comment by ashleygwilliams** [comment]
yup, @snopeks. the docs currently state upfront in the roles page that they cannot be changed. however, i am going to:

- explicitly state not to delete the super admin
- explicitly state not to delete the developers team

PR incoming
