### ISSUE TITLE
"See also" `npm` link leads to 404

### ISSUE THREAD

**Issue by verpixelt** [npm/docs#477]
Hey y'all,
on [https://docs.npmjs.com/cli/npm](https://docs.npmjs.com/cli/npm) the last `npm` link in the "See also" section links to [https://docs.npmjs.com/undefined/npm](https://docs.npmjs.com/undefined/npm) (404). I'd like to fix that. On other pages the `npm` link leads to the page([https://docs.npmjs.com/cli/npm](https://docs.npmjs.com/cli/npm)) I found the dead link on. Because it doesn't make sense to link to the page itself I'd propose to delete it completely from this site.

**Comment by ashleygwilliams** [comment]
hey @verpixelt ! good catch. this bug occured when i finally landed those clickable links #411 

here is the page you would need to PR https://github.com/npm/npm/blob/master/doc/cli/npm.md
(it is considered part of the CLI docs, so it lives in a separate repo)

let me know if you need help making a PR!

**Comment by verpixelt** [comment]
I've opened the PR. Everything correct https://github.com/npm/npm/pull/10719? Is there something I should add?

**Comment by othiym23** [comment]
The fix has been landed as npm/npm@b6a53b889c948053dcbf6d7aab9ad1cd4226dc32, so this will get pushed to docs when `npm@3.5.3` becomes `npm@latest` in a week or so. Thanks again, @verpixelt!
