### ISSUE TITLE
Consider adding a page on tags as a concept

### ISSUE THREAD

**Issue by cvrebert** [npm/docs#486]
It might be more natural to link mentions of tags to new dedicated page (ala https://docs.npmjs.com/misc/scope) rather than linking to the page about the command that manipulates tags (https://docs.npmjs.com/cli/dist-tag). And the dedicated page might be slightly easier to understand than https://docs.npmjs.com/cli/dist-tag , which starts out *in medias res* talking about manipulating tags before having explained what the heck tags are.

**Comment by ashleygwilliams** [comment]
hi @cvrebert this is a great suggestion.

the docs you linked to actually reside in the CLI repo (npm/npm), but i think you are right that they should be mentioned in the guides. PRs welcome!

**Comment by MitchLillie** [comment]
Happy to help on this one. To clarify: would this page live in npm/docs/content/getting-started (or somewhere else in this repo that makes sense), or in npm/npm/doc/misc (where the linked scope docs live)?

**Comment by cvrebert** [comment]
`misc` seemed appropriate to me since dist tags are a concept, like the other stuff in `misc`, but I'm no npm docs guru.

**Comment by ashleygwilliams** [comment]
hi @MitchLillie -- i'd put it in getting started for now. i'd like to break that guide up into smaller guides, with one focused on "publishing packages"

NB: `misc` lives in the CLI repo and is likely getting deprecated/moved here soon :)

**Comment by MitchLillie** [comment]
Sounds good @ashleygwilliams! I'll get cracking

**Comment by ashleygwilliams** [comment]
closing! merged in #551
