### ISSUE TITLE
There is no explanation for "npm test [-- <args>]" in docs

### ISSUE THREAD

**Issue by alex75ita** [npm/docs#490]
In this page, *https://docs.npmjs.com/cli/test*, there is no explanation for _--args_ parameter.
I was searching a way to exclude some files from being tested and I just start from this page.
Why is this unexplained? It is miss or the parameter dosn't exists at all?.

Thanks,
Alessandro

**Comment by KenanY** [comment]
@alex75ita Since `npm test` is an alias for `npm run-script test` you can check out [the `npm run-script` docs](https://docs.npmjs.com/cli/run-script) for information on passing arguments to scripts. I guess the `npm test` doc could have the same sentence that `npm start` already has:

> As of `npm@2.0.0`, you can use custom arguments when executing scripts. Refer to npm-run-script for more details.

**Comment by alex75ita** [comment]
"<code>npm test</code> is an alias for <code>npm run-script test</code>" 
This is the "right" information, in my opinion.
(How it is supposed one know this?)

Thank you Kenan
