### ISSUE TITLE
Avoidance of installation of duplicate modules and multiple dependency trees

### ISSUE THREAD

**Issue by ganeshkbhat** [npm/docs#493]
Is it how it is supposed to be?

When I install a project with a node module and if it has a dependency then it installs the dependency in its own `node modules` folder. Which is perfectly fine. But I am facing these following issues:

First: The issue arises when there are more then 3-4-5 or more dependency level trees (eg: `node_modules/new-extension/node_modules/somedep/node_module/xx/node_modules/` ....and so on). 

Second: Problem is that many node modules tend to have some common dependencies. NPM tends to install all of them again and again in all the places where dependencies are needed in specific parent node modules directory. (eg: `node_modules/mod1/node_modules/samemodule/node_module/`... AND `node_modules/mod2/node_modules/samemodule/node_module`). It does not map package.json parsing and combining to install one dependenc-y/ies for all. 

Major redundancy issues are created for a project this way. Any work around to avoid this? I have a 300 MB project size (little exaggerated) for a production distribution of 300 KB (redundancies removed) when using some good tools - not naming them.

**Comment by KenanY** [comment]
@ganeshkbhat Is this with `npm@2`? Have you tried out `npm@3`?

**Comment by ganeshkbhat** [comment]
Thanks. Resolved. node@5.3.0 had installed npm@2.x. upgrade to npm@3.5.3 resolved lot of issues. How is the behavior of multiple versions of x-module installation with some versions duplicated? Eg: xmod installed with different versions are installed as sub-folders. But the behavior is this xmod@2.6 (3 sub/dep node_modules folders - duplicated), xmod@1.9 (1 sub node_modules folder), xmod@0.1 (2 sub/dep node_modules folder - duplicated). Is this the expected behavior of npm or npm parsers them in main node_modules folder with version numbered folder once - this is surely desirable? +1

**Comment by ashleygwilliams** [comment]
hi! this should be solved by documentation here #479. closing.

**Comment by ganeshkbhat** [comment]
I do not understand what you mean. Did you mean it has been taken care of? I still have redundancy issues which I described. Or did you mean - https://github.com/npm/docs/pull/479 as in `+Instead of attempting to resolve module B to a single version, +npm puts both versions of module B into the tree, each version +nested under the module that requires it.` Is this going to be addressed for duplication of versions as well or is it taken as a accepted behavior to duplicate?
