### ISSUE TITLE
Why doesn't npm dedupe run after every npm install?

### ISSUE THREAD

**Issue by sunnyrjuneja** [npm/docs#524]
@ashleygwilliams tweeted an article explaining how to use npm dedupe (https://docs.npmjs.com/how-npm-works/npm3-dupe). I tweeted her asking why npm dedupe doesn't run after every npm install. She recommended I file it as an issue (https://twitter.com/ag_dubs/status/682294607032528896).

**Comment by ashleygwilliams** [comment]
hi! personally, i think you bring up a very interesting point-- and i think @iarna (one of our CLI engineers, took lead on npm3 design) agrees => https://twitter.com/ReBeccaOrg/status/682847766314258432

perhaps refile this as a feature request on the npm repo? https://github.com/npm/npm/issues
