### ISSUE TITLE
Clarify error when adding a tag that is valid semver

### ISSUE THREAD

**Issue by M-Zuber** [npm/docs#531]
Per https://docs.npmjs.com/cli/dist-tag#caveats the value provided to the `--tag` flag can not be valid semver.
But when I run `npm publish --tag v0.0.3-pre` for example the output is:
` Tag name must not be a valid SemVer range: v0.0.4-0`

This is confusing as `must` can also be understood as: it seems to not be valid, so change it to a valid semver value.

` Tag name can not be a valid SemVer range: v0.0.4-0` would be much clearer

**Comment by ashleygwilliams** [comment]
hey! thanks for filing! this is an issue with the CLI error output and the docs pulled in from the CLI so i've filed an issue on your behalf there: https://github.com/npm/npm/issues/11025

i'm also looking to write a guide on tags, see this issue: https://github.com/npm/docs/issues/486

thanks!
