### ISSUE TITLE
still wait on loading... and nothing happen

### ISSUE THREAD

**Issue by talsal** [npm/docs#534]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'tsc:w' ]
2 info using npm@3.5.2
3 info using node@v5.2.0
4 verbose run-script [ 'pretsc:w', 'tsc:w', 'posttsc:w' ]
5 info lifecycle angular2-quickstart@1.0.0~pretsc:w: angular2-quickstart@1.0.0
6 silly lifecycle angular2-quickstart@1.0.0~pretsc:w: no script for pretsc:w, continuing
7 info lifecycle angular2-quickstart@1.0.0~tsc:w: angular2-quickstart@1.0.0
8 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/XXXXXX/Documents/angular2-quickstart/node_modules/.bin:/usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/XXXXXX/Documents/angular2-quickstart/node_modules/.bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle angular2-quickstart@1.0.0~tsc:w: CWD: /Users/xxxxxx/Documents/angular2-quickstart
11 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Args: [ '-c', 'tsc -w' ]
12 silly lifecycle angular2-quickstart@1.0.0~tsc:w: Returned: code: 1  signal: null
13 info lifecycle angular2-quickstart@1.0.0~tsc:w: Failed to exec tsc:w script
14 verbose stack Error: angular2-quickstart@1.0.0 tsc:w: `tsc -w`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at EventEmitter.emit (events.js:173:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at ChildProcess.emit (events.js:173:7)
14 verbose stack     at maybeClose (internal/child_process.js:819:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
15 verbose pkgid angular2-quickstart@1.0.0
16 verbose cwd /Users/xxxxx/Documents/angular2-quickstart
17 error Darwin 15.2.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "tsc:w"
19 error node v5.2.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error angular2-quickstart@1.0.0 tsc:w: `tsc -w`
22 error Exit status 1
23 error Failed at the angular2-quickstart@1.0.0 tsc:w script 'tsc -w'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-quickstart package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     tsc -w
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-quickstart
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-quickstart
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ashleygwilliams** [comment]
hello! this looks like an error report for the npm CLI, however, this is the docs repo. please refile on npm/npm. thanks!

**Comment by talsal** [comment]
The problem was just mistake that i put in the package file: "package" and not directly {. works good
