### ISSUE TITLE
Alow package.json "engines" to support LTS

### ISSUE THREAD

**Issue by SteveALee** [npm/docs#538]
Its seems useful to be able to specify you want the latest in a [LTS version](https://github.com/nodejs/LTS/)  when the highest version is not specifically known.

1) You don;t know what the latest LTS version is so following format could work
{ "engines" : { "node" : ">=4.2LTS" } }
 
2) Would be useful to get an alert when a later LTS version is available Eg later versin with same even major. This would require an online check of latest versions

I think this is safe as long as new LTS releases do not break anything (minor version change only)

**Comment by ashleygwilliams** [comment]
hello! it seems you are requesting a feature of npm, but this is the docs repo. could you refile there please? thanks!

**Comment by SteveALee** [comment]
Apologies. I followed a link form a web page and obviously misunderstood the intent.
