### ISSUE TITLE
add "decscription" behavior to using package.json page

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/docs#556]
<img width="960" alt="screen shot 2016-01-13 at 12 53 15 pm" src="https://cloud.githubusercontent.com/assets/1163554/12302727/b2db75e8-b9f4-11e5-8386-79c6434dca7e.png">

from @snopeks

**Comment by ashleygwilliams** [comment]
hey @snopeks would you be interested in me walking you through how to do this PR? i think you've got a great grasp on what needs to be doc'd. lemme know!

**Comment by PrototypeAlex** [comment]
I'm happy to pick this one up, found what's going down with this here: https://github.com/npm/normalize-package-data/blob/0aa15b23116f2dfd086f1ed6bf213cbb7e7490dd/lib/extract_description.js 

Here's my attempt, probs needs some wordsmithing as I'm not the best at making things understandable :smile_cat: 

# description

Put a description in it. It's a string. This helps people discover your package, as it's listed in npm search. The default value is extracted from the project's README.md or README if one exists, and will be the first block of text, before the first heading, that isn't the first line heading.

**Comment by ilanbiala** [comment]
I opened a PR that should fix this. It would be great to get any feedback from you guys.

**Comment by ashleygwilliams** [comment]
hey @ilanbiala i'll check that out right now!
