### ISSUE TITLE
no `npm team ls org user`

### ISSUE THREAD

**Issue by ashleygwilliams** [npm/docs#598]
remove this per https://github.com/npm/npm/issues/11491

**Comment by ashleygwilliams** [comment]
remove this from the orgs/team page! it does not exist!

**Comment by Charlotteis** [comment]
Yo @ashleygwilliams, is the task:

* [ ] Fork the repository
* [ ] Create a new branch
* [ ] Remove the ['List teams a member belongs to'](https://github.com/npm/docs/blob/5a32639c977cdbee65be87ed2cbac143d428c120/content/orgs/teams.md#list-teams-a-member-belongs-to?) section
* [ ] Commit changes
* [ ] Open a Pull Request
* [ ] If all of the above goes well, you're a contributor to the npm docs page!

If so, I'd love to tweet about it from @yourfirstpr, I just want to clarify that this is the task, first.

:v:

**Comment by ashleygwilliams** [comment]
yes! perfect 🤗

**Comment by SteveAzz** [comment]
I can take it later tonight :+1:

**Comment by jartek** [comment]
Can i take this?

**Comment by SteveAzz** [comment]
@jartek Go ahead then

**Comment by jartek** [comment]
@SteveAzz Thank you
