### ISSUE TITLE
Documentation: fixing permission issues

### ISSUE THREAD

**Issue by hkrdrm** [npm/docs#602]
I messed my permissions up on /usr/bin/ with this command.  Completely my fault I read the warning but saw the number 2. right below it and went straight to that command thinking it was Option 2.  Maybe some clearer distinction between that step 2 and option 2.
 
WARNING: If the displayed path is just /usr, switch to Option 2.

2. Change the owner of npm's directories to the name of the current user (your username!):

**Comment by Simpler1** [comment]
I just did exactly the same thing.  Please remove option 1.  It is extremely destructive and Option 2 should be the common solution for this issue anyway.

Thanks

**Comment by nmai** [comment]
@hkrdrm Just submitted a PR, take a look if you have a chance and let me know if it can be further improved!

**Comment by hkrdrm** [comment]
That looks good to me much more clearer now.
