### ISSUE TITLE
Transcript of video materials or self-provided closed captioning

### ISSUE THREAD

**Issue by jdax** [npm/docs#612]
On the first getting started [page](https://docs.npmjs.com/getting-started/what-is-npm)  there is a video with no indication of either accurate self-provided closed captioning (and when the user does click on YouTube's closed captioning, it says it is auto-generated), or a way to get a transcript of the materials. Users on older (and slower) internet connections cannot quickly access video materials and rely on transcripts, and users with disabilities around hearing ability or audio learning difficulties may find the lack of transcripts or accurate captioning an impediment to quickly getting the information they need to use npm. 

ETA: PR incoming for this specific page this evening, as I go through the guide if I find any more missing I will update this issue, and see if I can add transcript to my PR.

**Comment by ashleygwilliams** [comment]
this is AWESOME. i can't begin to tell you how much i appreciate this :) the community will really benefit!
