### ISSUE TITLE
Sync website and actual docs

### ISSUE THREAD

**Issue by just-boris** [npm/docs#636]
Figured out that information on this page: https://docs.npmjs.com/files/package.json doesn't match with actual information here: https://github.com/npm/npm/blob/master/doc/misc/npm-scripts.md
See "Default values" section, about install/preinstall script.

I was misled about this and made a bug here: https://github.com/alexanderGugel/ied/issues/101 which is not good

**Comment by ashleygwilliams** [comment]
hey! yes, i am sorry you ran into a problem. this should be fixed by the end of next week.

**Comment by oprogramador** [comment]
@just-boris @ashleygwilliams IMO we can close this issue
