### ISSUE TITLE
add an unlinked docs page for that new integration page

### ISSUE THREAD

**Issue by cowperthwait** [npm/docs#672]
After 8p PDT on 5/23, @bcoe needs to commit and merge a new docs page with documentation for that integration we’ll announce at 6a PDT on 5/24. Ben has a link to a gist with final approved copy in his email, in the “GTM” group thread between us and PR for the integration partner.

**Comment by ashleygwilliams** [comment]
hey @cowperthwait i think this happened? please reopen if i am mistaken

**Comment by 609141912** [comment]
Hallo;)
