### ISSUE TITLE
Fixing npm permissions - Windows 10 Bash Ubuntu

### ISSUE THREAD

**Issue by cadupedroni** [npm/docs#677]
I'm using bash ubuntu on windows 10, but I'm with permission issues with the npm to install any package is ionic, cordova and etc

Can anyone help fix this problem on Windows 10?

Version Ubuntu 14.04

**Comment by virgil9306** [comment]
What's the actual error message?

**Comment by casz** [comment]
NPM has a documented how to fix permission issues.
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by cadupedroni** [comment]
Is resolved was allowed to directory.
