### ISSUE TITLE
The link to Homebrew in fixing-npm-permissions (getting-started part) results in 404

### ISSUE THREAD

**Issue by m4jing** [npm/docs#695]
The original page is at **getting-started/fixing-npm-permissions**:

<https://docs.npmjs.com/getting-started/fixing-npm-permissions>

In [Option 3](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-3-use-a-package-manager-that-takes-care-of-this-for-you),

![npm-docs-bug-link-404](https://cloud.githubusercontent.com/assets/2697870/15641925/9cb6f2c6-2676-11e6-8bdd-4a1381aa6dea.jpg)

The link to Homebrew is <https://docs.npmjs.com/getting-started/brew.sh>, which will result in a 404 page.

Please help fix, thanks a lot :smile:

**Comment by KenanY** [comment]
Will be fixed by https://github.com/npm/docs/pull/641.

**Comment by DamnedScholar** [comment]
Are you sure?

**Comment by m4jing** [comment]
@DamnedScholar A broken link, I'm sure about it.

**Comment by DamnedScholar** [comment]
The question was regarding #641, which has been sitting around for quite a while even though it's a simple typo fix.

**Comment by m4jing** [comment]
OK, I know it. Hope it'll be OK soon...:relieved:

**Comment by kellyjandrews** [comment]
Looks like #641 was merged - this can probably be closed now.

**Comment by m4jing** [comment]
OK. Thanks.
