### ISSUE TITLE
The documentation is not print-friendly

### ISSUE THREAD

**Issue by sorcamarian** [npm/docs#697]
# Print view
- "What is npm?" (one section - https://docs.npmjs.com/getting-started/what-is-npm)

![image](https://cloud.githubusercontent.com/assets/12509753/15664484/f6a4355a-270c-11e6-9b4b-d4fc5c7533eb.png)
- "All Docs" (all sections - https://docs.npmjs.com/all)

![image](https://cloud.githubusercontent.com/assets/12509753/15664563/a783b968-270d-11e6-9321-f5ab07b04715.png)
## Proposal

[CSS3 @media print rule](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) can be used in order to hide certain elements and to position others adequate.

For example:
- hide all videos
- on the page "All Docs'(all sections listed), show table of contents. (inspire from: https://nodejs.org/api/all.html)
- on "one section" pages("What is npm?"), obove the title, add: **previous section name(if exists) > current section name > next section name(if exists)**
  and above these, add the parent section name (example: ![print-friendly_one_section_pages](https://cloud.githubusercontent.com/assets/12509753/15665557/6f80557e-2714-11e6-8ab4-6aacf1aa9100.jpg))

**Comment by stevemao** [comment]
linking https://github.com/nodejs/node/issues/6743 and https://github.com/nodejs/node/pull/6748
Maybe you want to open an issue at npm instead?

**Comment by kellyjandrews** [comment]
Have the initial portion of this ready to go here - https://github.com/kellyjandrews/docs/tree/issue-697

Currently working on the section portion. I can submit the PR now and update when thats done - let me know how you prefer to handle that.

**Comment by kellyjandrews** [comment]
Working on the section titles portion of this now.

**Comment by kellyjandrews** [comment]
@ashleygwilliams - let me know if this works for you, or if it needs tweaked at all. Thanks!
