### ISSUE TITLE
Add FAQ section to npm Enterprise Add-Ons

### ISSUE THREAD

**Issue by nexdrew** [npm/docs#720]
To help clarify some things for customers such as:
- Do third party add-ons work for public and private packages or only public packages?
- Is my private package code exposed to third party add-ons and, if so, how?
- Can I disable or remove an add-on once it's been installed, and, if so, how?

And any others we can think of.

**Comment by ashleygwilliams** [comment]
hey @nexdrew i'mma close this since we have the new npme docs now. lemme know if you want me to migrate this issue over there!
