### ISSUE TITLE
Documentation link not working - https://docs.npmjs.com/getting-started/using-a-package.json

### ISSUE THREAD

**Issue by madhurahuja** [npm/docs#722]
This link throws a JSON error SyntaxError: Unexpected identifier.

**Comment by KenanY** [comment]
Looks fine to me.

**Comment by madhurahuja** [comment]
Still getting that error- Attached the screenshot.

![npmjsweberror](https://cloud.githubusercontent.com/assets/1109523/17025099/08f24478-4f20-11e6-9b2b-3ce33852e483.png)

**Comment by madhurahuja** [comment]
The reason for this to happen is the way the URL is constructed. Chrome extensions like **PrettyJSON** and **JSONView**, look for **.json** extension in the URL and try to parse it. Since the page has **.json** in the end, these plugins try to parse a non-JSON response. Once I disable these plugins page works fine.

**Comment by KenanY** [comment]
Hmm, I wonder if it would be possible for these extensions to parse the `Content-Type` header rather than simply using the end of the URL. Technically there's nothing wrong with having a page end in `.json` but not serve actual json.

**Comment by madhurahuja** [comment]
I agree.
