### ISSUE TITLE
Document how search rank is determined

### ISSUE THREAD

**Issue by wheresrhys** [npm/docs#730]
I own 2 components - fetch-mock and fetch-link. fetch-link is far higher up the search results for 'fetch', despite being far less active, so I figure there's something wrong in the fetch-mock repo which causes it to be ranked much lower. My current hunch is that you favour repos packages with MIT licences.

So firstly, is that assumption correct? And secondly, the only documentation I could find about search rank is in an old blog post http://blog.npmjs.org/post/80789086446/nicer-perusal-method, but given the case of the two packages I own, it seems like the intended behaviour is broken as the most popular of the two packages is ranked lower

**Comment by kwhitley** [comment]
Also very curious about the rankings... 

My own [apicache](https://www.npmjs.com/package/apicache) has more stars/downloads than most things that appear under "api cache", yet appear far down the listing for that search... Not sure what has dinged it!
