### ISSUE TITLE
use something less jargony than "tl;dr"

### ISSUE THREAD

**Issue by jonhp** [npm/docs#738]
[https://docs.npmjs.com/how-npm-works/packages](url)

what is the point of the "tl;dr" header? "too long; didn't read" or ??? or just confusing?

**Comment by KenanY** [comment]
@jonhp Yup, it stands for _too long; didn't read_, and is intended to be a summary of the entire page.

**Comment by shaundon** [comment]
That link appears to be producing a 404 now - has something moved?

**Comment by KenanY** [comment]
Proper link: <https://docs.npmjs.com/how-npm-works/packages>
