### ISSUE TITLE
npm-zepto error on windows

### ISSUE THREAD

**Issue by HioryLiu** [npm/docs#741]
npm ERR! npm-zepto@1.1.7 install: `script/build`
npm ERR! Exit status 1
npm ERR! Failed at the npm-zepto@1.1.7 install script 'script/build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the npm-zepto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     script/build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs npm-zepto
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls npm-zepto
npm ERR! There is likely additional logging output above.
I have updated my node,but the error persits.

**Comment by ashleygwilliams** [comment]
hi! this is an issue with the npm-zepto package. you'll need to file this on that project. closing.
