### ISSUE TITLE
npm enterprise how to update ssl certificate

### ISSUE THREAD

**Issue by kzahel** [npm/docs#743]
How can I update an existing NPM enterprise install's SSL certificate. Say for example I have an already running NPME enterprise running with a self signed certificate, and now I have a real certificate. I don't see anywhere in the dashboard where I can update the certificate. Is there a filepath where I can manually update it on the filesystem, or a secret URL I can go to?

**Comment by kzahel** [comment]
Nevermind. looks like /console/settings is the place to go.

**Comment by kzahel** [comment]
I tried both uploading and by manually putting on server in the console, but the admin console does not seem to use the certificate I upload.

**Comment by ashleygwilliams** [comment]
the npme docs now live here: https://github.com/npm/npme-docs ! i've moved your issue over there :)
