### ISSUE TITLE
enquiry

### ISSUE THREAD

**Issue by frcmak** [npm/docs#754]
1. Is Internet access required when running npm uninstall of node modules installed locally or globally

2. What's the action of npm uninstall

**Comment by ashleygwilliams** [comment]
hi! 

1. internet access is not required when running npm uninstall for either local or global installs.
2. you can investigate the action here: https://github.com/npm/npm/blob/70cc6a7b6cae114ef9fb5a9b7b1a712dad454075/lib/uninstall.js - it's p straightforward, but let me know if you need help reading the code :)

**Comment by ashleygwilliams** [comment]
will close, but please feel free to reopen if you still have qs!
