### ISSUE TITLE
enquiry

### ISSUE THREAD

**Issue by frcmak** [npm/docs#755]
Hi All

Please give me advice that of test cases for node, for node module "electron", for 2 cases...
1.  On a Raspberry Pi without node module "Electron"
   Is Internet access required when running uninstall electron? So, when I do a global install of electron, what does it mean, what happens on a raspberry Pi? Can I do exactly the same, manually, what a global install does?
2. On a Raspbery Pi with node node module "Electorn"
   Is Internet access required when running uninstall electron? So, when I do a global install of electron, what does it mean, what happens on a raspberry Pi? Can I do exactly the same, manually, what a global install does?
3.  For both cases, how do I uninstall Electron globally? And during the uninstall, what actaully happens on the Raspberry Pi? Can I do it manually?

Please advise,

Many thanks.

Regards,
Frankie

**Comment by ashleygwilliams** [comment]
hi! @frcmak - npm uninstall does not hit the network, so you do not need internet access for any type of install.

an install of any type with npm fetches the package metadata, then fetches the package tarball, unzips the tarball and installs it in the `node_modules` folder. it then does the same for the packages dependencies. what the directory structure looks like depends on what version of npm you use and you can learn more about that here: https://docs.npmjs.com/how-npm-works/npm3

you can npm install directly from a tarball that is on disk, i.e. `npm install package-1.0.0.tgz` and it should do the same thing except it won't need to make a request for it on the network. you can make a tarball by running `npm pack`.

to uninstall something globally you can run `npm uninstall <pkg> -g`. this removes the package from your global node modules directory (depends on device).

please reopen this if i have not fully answered your questions! thanks!
