### ISSUE TITLE
npm shrinkwrap does include dev dependencies without --dev flag, the docs say otherwise.

### ISSUE THREAD

**Issue by ericpitcher** [npm/docs#780]
Shrinkwrap page https://docs.npmjs.com/cli/shrinkwrap

It states:

> Since npm shrinkwrap is intended to lock down your dependencies for production use, devDependencies will not be included unless you explicitly set the --dev flag when you run npm shrinkwrap. If installed devDependencies are excluded, then npm will print a warning. If you want them to be installed with your module by default, please consider adding them to dependencies instead.

Running npm shrinkwrap on npm 4.0.2 without the --dev flag will still include the dev dependencies in the shrinkwrap file. No warninngs printed.

Is this new intended behavior and the docs are wrong or is this a mistake in the source?

**Comment by diminutivesloop** [comment]
Yeah this is definitely inconsistent with the [documentation](https://github.com/npm/npm/blob/latest/doc/cli/npm-shrinkwrap.md) in the main repo which says:

> Starting with npm v4.0.1, devDependencies are included when you run npm shrinkwrap and follow the usual rules as to when they're installed. As of npm v3.10.8, if you run npm install --only=production or npm install --production with a shrinkwrap including your development dependencies they won't be installed. Similarly, if the environment variable NODE_ENV is production then they won't be installed. If you need compatibility with versions of npm prior to v3.10.8 or otherwise don't want them in your shrinkwrap you can exclude development dependencies with: npm shrinkwrap --only=prod or npm shrinkwrap --production.

**Comment by ashleygwilliams** [comment]
so the source of truth for those docs is in the CLI repo. this simply means that the version of the CLI docs is not up to date in this repo! i'll update it and deploy and ideally this should be fixed :) thanks for filing
