### ISSUE TITLE
fixing-npm-permissions.md instruction can kill your server

### ISSUE THREAD

**Issue by istarkov** [npm/docs#786]
[Here](https://github.com/npm/docs/blob/master/content/getting-started/fixing-npm-permissions.md) this instruction

```shell
sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}
```

change the ownership of sudo command on `ubuntu 12.04` (haven't checked on others) 
And if root user is not allowed, (but system have user with sudo permissions) this cause inability to execute any command which needs a sudo rights.

The error is
```
sudo: must be setuid root
```

There is no simple way to fix it, as you can't change permissions back because of this error. (Having that server is remote and you don't have access to some modes)

**Comment by KenanY** [comment]
@istarkov Duplicate of https://github.com/npm/docs/issues/745?

**Comment by istarkov** [comment]
Yes, 
Will close.
