### ISSUE TITLE
Drop support for NodeJS v0.12

### ISSUE THREAD

**Issue by ndelangen** [npm/docs#791]
This project has a travis test-configuration for NodeJS 0.12. Can this be dropped in favour for only supported NodeJS 4+.

This way we can start using the improvements in NodeJS 4+, like the ES6 features. NodeJS 6+ would be even better, since it's the lowest that determines the features we can use.

In which actual NodeJS version is this hosted?

**Comment by ashleygwilliams** [comment]
it's on 4! if you'd like to make a PR to travis i'll happily merge

**Comment by ndelangen** [comment]
Will do!

**Comment by ndelangen** [comment]
Any reason to not start hosting it on NodeJS v6 ? 🤠

**Comment by ashleygwilliams** [comment]
i'm sure we will soon, but we'll do when we roll all our servers over :) (that's a LOT of servers)
