### ISSUE TITLE
"Scoped packages" docs has broken link to "private-modules" docs

### ISSUE THREAD

**Issue by ejfrancis** [npm/docs#829]
The "private-modules" link at the end of the "scoped packages" documentation is broken https://docs.npmjs.com/getting-started/scoped-packages

**Comment by CarolynWriter** [comment]
This link works now.

**Comment by CarolynWriter** [comment]
Link works.

**Comment by MatthiasDebaere** [comment]
[https://www.npmjs.com/package/private-modules](https://www.npmjs.com/package/private-modules) seems to be broken again, I get the 404 wombat..
