### ISSUE TITLE
total lack of versioning information and documentation for older versions

### ISSUE THREAD

**Issue by minusf** [npm/docs#846]
The nodejs.org download page recommends for "most users" their LTS release
(at the time of writing `Latest LTS Version: v6.11.1 (includes npm 3.10.10)`)

However https://docs.npmjs.com is always for the latest npm release. This effectively means no documentation for npm that is bundled with LTS nodejs.

There is also a painful lack of version information for options and features throughout the documentation leaving users guessing *when* a given feature was introduced and whether it is available in the version they might be using.

Compare this with documentation for other projects like python:

**os.path.commonpath(paths)**

Return the longest common sub-path of each pathname in the sequence paths. Raise ValueError if paths contains both absolute and relative pathnames, or if paths is empty. Unlike commonprefix(), this returns a valid path.

*Availability:* Unix, Windows

*New in version 3.5.*

*Changed in version 3.6:* Accepts a sequence of path-like objects.

**Comment by CarolynWriter** [comment]
We have started to add versioning information as new features are developed and documented. Thanks for this request!
