### ISSUE TITLE
Command in the manual causes lose of sudo access

### ISSUE THREAD

**Issue by tahsinozden** [npm/docs#851]
In the following page "https://docs.npmjs.com/getting-started/fixing-npm-permissions", the following command causes problems with sudoer user in Fedora Workstation 25.
 `sudo chown -R $(whoami) $(npm config get prefix)/{lib/node_modules,bin,share}`

This is the error after running the command.
`sudo /usr/libexec/sudoers.so must be owned by uid 0`

**Comment by KenanY** [comment]
Duplicate of https://github.com/npm/docs/issues/745?

**Comment by tahsinozden** [comment]
@KenanY yes it seems it is duplicate. sorry for that.
