### ISSUE TITLE
redundant 'description' field on using-a-package.json page in example json`

### ISSUE THREAD

**Issue by dhiltbrand** [npm/docs#857]
Hi, there are two 'description' fields in the example package JSON that is offered as an example of a package.json structure generated by "npm init --yes"

The section in question is found here:

https://docs.npmjs.com/getting-started/using-a-package.json#the---yes-init-flag

There should only be one 'description' field listed in the JSON, as two makes it malformed JSON and might lead to unpredictable behavior across different parsers.

Thanks for the hard work and great tool y'all make available to us with NPM though!

**Comment by KenanY** [comment]
https://github.com/npm/docs/pull/819

**Comment by CarolynWriter** [comment]
Fixed! Thank you! https://docs.npmjs.com/getting-started/using-a-package.json

**Comment by CarolynWriter** [comment]
Fixed!
