### ISSUE TITLE
Put the latest version of npm in a prominent place in the website

### ISSUE THREAD

**Issue by kevinburke** [npm/docs#861]
I'm trying to find out what the latest version of NPM is, (and whether the version I am running locally is up to date). Googling "npm latest version" doesn't return very promising answers.

It would be nice if https://www.npmjs.com/ or https://www.npmjs.com/get-npm contained a string saying "The latest version of npm is vX.Y.Z".

**Comment by mhverbakel** [comment]
Every page of https://docs.npmjs.com/ contains a footer with the latest stable version number.

**Comment by faazshift** [comment]
@kevinburke You can also just run `npm view npm version` from anywhere you have `npm` installed.

**Comment by CarolynWriter** [comment]
Hi Kevin. Did these answers help, or do you want the version to be featured prominently other locations as well?

**Comment by kevinburke** [comment]
Hey! I guess it's tough since I know where to look now (the footer). I
would maybe check based on whether you can find the answer easily from the
results of a Google search for "npm latest version" or maybe ask 3 or 4
people "what's the latest version of npm" and see how they find the
answer...


--
Kevin Burke
925.271.7005 | kev.inburke.com

On Mon, Nov 27, 2017 at 5:18 PM, Carolyn McDonough <notifications@github.com

**Comment by CarolynWriter** [comment]
You are correct. . . it is not easy to find the latest version by using Google. . . I will elevate this to the correct team.
