### ISSUE TITLE
Feature Request: Ability to make "dependencies" & "devDependencies" dynamic.

### ISSUE THREAD

**Issue by kaustubhtalathi** [npm/docs#884]
The current situation.
Currently all dependencies are split into "dependencies" & "devDependencies". I think almost everyone knows what they stand for. "dependencies" are required while running the app & "devDependencies" are required while developing the app.

How and why the current situation is problematic.
I was explaining someone about "dependencies" & "devDependencies" who didn't knew the difference between the two. While discussing, there was a thought of renaming "dependencies"=>"production" & "devDependencies"=>"developers".  I am not sure if this functionality exist but it would be good to set these keys dynamically as per the project/team requirement.

A detailed proposal or pull request that demonstrates how the problem could be solved.
Allowing npm to configure an alias for these names and treat it same.

A use case – who needs this feature and why?
This is not a need but a better to have feature.

Any caveats.
I am used to these terms but changing the names in package.json might create confusion among the team unless it is specified in a readme file.

**Comment by isaacs** [comment]
Hi.  This repo is for the documentation specifically, not for npm itself.

I think that this suggestion probably belongs over at https://github.com/npm/npm/issues

That being said, what you're suggesting is a _very_ major change from what exists today, and I am beyond doubtful that the benefits outweigh the costs.  A _lot_ of stuff looks at these fields in `package.json` files, in the npm registry and website systems, and in many other systems and services across the internet.
