### ISSUE TITLE
05 - Using a `package.json`link is broken

### ISSUE THREAD

**Issue by labtopia** [npm/docs#904]
When I click on that link, it takes me here:

https://docs.npmjs.com/getting-started/using-a-package.json

This page displays this error:

Unable to parse JSON.

Error Message:

SyntaxError: Unexpected identifier

Response:

npmjs.com

**Comment by CarolynWriter** [comment]
Thank you! I have notified the correct team.

**Comment by lhywell** [comment]
![image](https://user-images.githubusercontent.com/1267061/33803554-13464c9c-ddce-11e7-914b-40b55b4a205c.png)
this page cannot open,404

**Comment by CarolynWriter** [comment]
When I click on that link from what you pasted, it works for me . . .I noticed that your URL has **.cn** at the end of docs.npmjs.com . Could that be the issue? Please let me know where you got the link that had the **.cn** in it. I highlighted this in a screen capture of your screen capture (attached)

![link to chapter 5 issue 904](https://user-images.githubusercontent.com/32074794/34133990-e365bd88-e40c-11e7-88d5-d93e43531d32.png)

**Comment by CarolynWriter** [comment]
Apologies, I see that .cn is China. I will follow up on this.

**Comment by CarolynWriter** [comment]
npmjs.com is not managed by npmjs.com, the domain lists 
Registrant Contact Email: wangsai@bootcss.com
So we do not have any way to fix this at this time. Please look for the information you seek on our official doc site, https://docs.npmjs.com/getting-started/using-a-package.json . Thank you!
