### ISSUE TITLE
Publishing npm packages -- using npm config ls not working as expected

### ISSUE THREAD

**Issue by aryzing** [npm/docs#908]
In the [Publishing npm packages](https://github.com/npm/docs/blob/master/content/getting-started/publishing-npm-packages.md) section, it recommends the user to test whether their account creation was successful:

> Test: Use `npm config ls` to ensure that the credentials are stored on your client.

However, that command does not produce any significant information related the actions the user has just performed. There is no trace of anything user-related. At least in my case, the output looks like

```
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v9.3.0 darwin x64"

; builtin config undefined
prefix = "/usr/local"

; node bin location = /usr/local/Cellar/node/9.3.0_1/bin/node
; cwd = /Users/aryzing/workspace/my-package
; HOME = /Users/aryzing
; "npm config ls -l" to show all defaults.
```

* Is there another command that the user can issue that would allow them to confirm that `adduser` worked successfully? 
* Is the currently proposed command of use anymore?

**Comment by CarolynWriter** [comment]
Hello, thanks for this comment. I have assigned this to myself and will address it the next time I work on this section.

**Comment by CarolynWriter** [comment]
Hi, the answer is to type npm whoami. I have updated the doc. The new version will be out hopefully by the end of this week!
