### ISSUE TITLE
Typos/Quick Corrections--this will be an ongoing header please create responses 

### ISSUE THREAD

**Issue by CarolynWriter** [npm/docs#927]
This will be an ongoing header for typos/quick corrections. Please add as a response under this header so that I can make this type of change on a schedule. I will see how this approach works.

**Comment by noahleigh** [comment]
Um, should #919 be included in this?

**Comment by CarolynWriter** [comment]
Hi I decided this is a bad plan. I am deleting this concept. So 919 can stand as it is. Thanks!

**Comment by CarolynWriter** [comment]
better to have typos on their own issues, on 2nd thought
