### ISSUE TITLE
Minor typo in 13 - How to use semantic versioning

### ISSUE THREAD

**Issue by zdoc01** [npm/docs#929]
When reviewing the table under "Semver for Publishers" on the "How to use semantic versioning" page, I noticed a typo in the last "CODE STATUS" cell. I believe "competebility" was intended to be "compatibility."

In other words, the cell should read:

"Changes that break backward compatibility"

**Comment by CarolynWriter** [comment]
Thank you, it's noted. The next time this doc is changed, this will be corrected.

**Comment by CarolynWriter** [comment]
Thank you for catching this, zdoc01 ! This is now fixed in draft mode and will be published by the end of the week.
