### ISSUE TITLE
"Before we start" section in "Working with private packages" chapter encourages users to run npm with sudo

### ISSUE THREAD

**Issue by tlakomy** [npm/docs#959]
I've noticed that in the docs, there's a mention of running `npm install` with `sudo`:

<img width="637" alt="screen shot 2018-02-23 at 11 20 53" src="https://user-images.githubusercontent.com/16646517/36593011-5de1a260-1898-11e8-9580-91ae1bd225d0.png">

Since a lot of users have had issues with `npm 5.7.0` while running it with `sudo`, I think it may be worth to remove `sudo` from that line of documentation to discourage users to ever run `npm` with `sudo`.

I'll create a PR for this change in a minute

**Comment by CarolynWriter** [comment]
Thank you! This is on the list for the next doc release! This clearly needs to be updated!

**Comment by tlakomy** [comment]
No problem! I already created a PR with the necessary change so it can be merged :)

**Comment by karlhorky** [comment]
#960 has been merged, so I guess this can be closed too?

**Comment by tlakomy** [comment]
Let me close it
