### ISSUE TITLE
Website encourages use of rejected package names

### ISSUE THREAD

**Issue by mindplay-dk** [npm/docs#967]
I spent the day curating a new package, and finally was ready to publish.

I decided on the package name having first seen [this](https://www.npmjs.com/package/drag-n-drop) page:

![image](https://user-images.githubusercontent.com/103348/37416089-362de458-27ad-11e8-94a8-698625ac45f4.png)

The page seemed to more than imply that this package-name would be, oh yes, mine.

Yet, upon attempting my first-ever `npm publish`, I was met with the following:

![image](https://user-images.githubusercontent.com/103348/37416249-915103e2-27ad-11e8-9aa0-c607c858a615.png)

Well, back to the drawing board for a new name 💔😢

Meanwhile, what would be really nice, is if the web-page wouldn't mislead me into thinking I can have just the package-name I want.

If a package name is too similar, clearly your servers know which package name(s) is/are too similar to the one I'd like, so I'd suggest instead displaying a "did you mean such-and-such?" page.

I'd appreciate it.

**Comment by KenanY** [comment]
Might be best opened over at <https://github.com/npm/www>.

**Comment by mindplay-dk** [comment]
Looks like I duplicated [this](https://github.com/npm/www/issues/312)

Thanks @KenanY 👍
